# Generated by Django 4.2.14 on 2025-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AbanGasPart', '0003_alter_item_catalog_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('گازی', 'Gas'), ('برقی', 'Electric')], max_length=50),
        ),
    ]
